# Build settings

port: 4000
markdown:  kramdown
permalink: /:lang/:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Milica Petrinjak"
description: "Powered by Jekyll and GitHub Pages"
author:      "Milica Petrinjak"

# Multilingual support
languages: ["en", "de"]
default_lang: "en"
