title: "Your Portfolio Title"
description: "An architecture portfolio showcasing my work."
baseurl: "" 
url: "https://yourgithubusername.github.io"

# 🔹 Default Language & Available Languages
default_lang: "en"
languages: ["en", "de"]

# 🔹 SEO Settings (These will be referenced in `settings.yml`)
seo:
  description_en: "An architecture portfolio showcasing projects and design concepts."
  description_de: "Ein Architekturportfolio mit Projekten und Designkonzepten."
  rel-author: "https://yourwebsite.com/author"
  rel-publisher: "https://yourwebsite.com/publisher"

# 🔹 Collections (for projects, blogs, etc.)
collections:
  projects:
    output: true
    permalink: "/:collection/:name"

# 🔹 Navigation (Use language keys)
menu:
  en:
    - name: "Projects"
      url: "projects"
    - name: "About"
      url: "about"
    - name: "Contact"
      url: "contact"
  de:
    - name: "Projekte"
      url: "projekte"
    - name: "Über mich"
      url: "ueber-mich"
    - name: "Kontakt"
      url: "kontakt"
