# Build settings
markdown: kramdown
permalink: /:lang/:categories/:title/
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Customise atom feed settings
title: "Milica Petrinjak"
description: "Powered by Jekyll and GitHub Pages"
author: "Milica Petrinjak"

# Multilingual support
languages: ["en", "de"]
default_lang: "en"
lang: "en"  # Set the default language for the site
