#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Experience',  url: 'experience'}
- {name: 'About',    url: 'about'}
- {name: 'Contact',  url: 'contact'}

#-------------------------------
# Projects Section

projects:
- {name: 'Conceptual architectural competition_Modular Prefabricated House',   url: 'proj-1'}
- {name: 'Generative AI',   url: 'proj-2'}
- {name: 'Creative Urban Regeneration of Smderevo Waterfront',   url: 'proj-3'}
- {name: 'Rehabilitation center on Avala', url: 'proj-4'}
- {name: 'Sustainable green neighborhood',  url: 'proj-5'}
- {name: '”Kala” research center',  url: 'proj-6'}
- {name: 'Wooden Japanese pavilion',  url: 'proj-7'}
- {name: 'Vračar luxury housing',  url: 'proj-8'}
- {name: 'Archaeological and Landscape Living Lab',  url: 'proj-9'}
- {name: 'Work projects interior design',  url: 'proj-10'}
- {name: 'Work projects exterior design',  url: 'proj-11'}

#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: 'https://www.instagram.com/mei_arch/'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/in/milica-petrinjak-a9828a82/'}
- {icon: 'envelope',  link: 'mailto:mailto:milicapetrinjak@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio by Milica Petrinjak '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''
